ALTER TABLE `event_settings`
  ADD COLUMN IF NOT EXISTS `consultationMode` enum('physician','automatic') NOT NULL DEFAULT 'physician';
--> statement-breakpoint
ALTER TABLE `event_care`
  ADD COLUMN IF NOT EXISTS `consultationMode` enum('physician','automatic') NOT NULL DEFAULT 'physician',
  ADD COLUMN IF NOT EXISTS `recommendationMeta` json NULL,
  ADD COLUMN IF NOT EXISTS `autoGenerationState` varchar(32) NOT NULL DEFAULT 'not_requested',
  ADD COLUMN IF NOT EXISTS `autoGenerationAttempts` int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `autoGenerationError` varchar(255) NULL,
  ADD COLUMN IF NOT EXISTS `autoGeneratedAt` timestamp NULL,
  ADD COLUMN IF NOT EXISTS `autoModel` varchar(64) NULL;
